### ISSUE TITLE
Any change to download from other site other than YouTube?

### ISSUE THREAD

**Issue by jamesbrindle** [ErrorFlynn/ytdlp-interface#1]
Hi,

I've just come across this repo - Excellent BTW!

yt-dlp can download from other types of sites, however, when trying with your app is says 'not a valid link'...

Any chance this can be used for other types of site?

**Comment by ErrorFlynn** [comment]
At the moment the program is focused on downloading from YT, simply because that's all I need it to do. I haven't even tried to use it for any other site, so I don't know how that compares to the YT usage. I will have to do some research and evaluate how I could evolve the interface to support other sites. I'm also not opposed to adding other features, like a queuing system for example. I don't know when any of that is going to happen, though. Keep an eye on the repo, I guess.

**Comment by jamesbrindle** [comment]
Cool.

yt-dlp seems to be able to recognise video streams from other sites without too much trouble. 

E.g.
yt-dlp.exe --list-formats https://vimeo.com/660749181

I forked your repo and attempted to build in the hope that I could simply remove / alter the URL validation. I was unable to get it to build though. I only have the most basic knowledge of C++ I'm afraid. I'll give it another try though at a later date.

Queuing is an excellent idea!

There is a python app available but it seems to be more trouble than its worth to get the application 'portable', and there are paid applications available, but I'm near sure most of them are shipped with virus's / too much adware, so your program is great!

**Comment by ErrorFlynn** [comment]
Just removing the link validation doesn't work (I just tried), because the output from `yt-dlp` is different, and needs to be parsed differently. At first glance, the differences seem to be fairly minimal though, so I might add Vimeo support in the next version!

**Comment by jamesbrindle** [comment]
Ahh...

Of course.

How about.... The option to not render the format list and just use yt-dlp
default? Then it may work on several types of site?

Kind regards,

Jamie

**Comment by ErrorFlynn** [comment]
That's a good idea, I'll see what I can do.

**Comment by allanlaal** [comment]
is this implemented?

**Comment by ErrorFlynn** [comment]
> is this implemented?

Yes.
