### ISSUE TITLE
N_m3u8DL-CLI

### ISSUE THREAD

**Issue by trimechee** [ErrorFlynn/ytdlp-interface#10]
Hello, Hello, since Ytdlp-Interface is aN amazing a graphical interface of command line tools , it well be great if our beloved Ytdlp-Interface add support for m3u8 with adding support for this tool updated recently N_m3u8DL-CLI :

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by ErrorFlynn** [comment]
It took me more than a year, but I have finally made a decision about this. Since ytdlp-interface has already gotten pretty complex, and other priorities compete for the limited development time, I've decided not to add support for N_m3u8DL-CLI. It's too much investment for too little benefit (especially since you can already download m3u8 with ytdlp-interface + yt-dlp).
