### ISSUE TITLE
Only chat is downloading 

### ISSUE THREAD

**Issue by MODKILLER1001** [ErrorFlynn/ytdlp-interface#101]
when using custom arguments `--embed-metadata --live-from-start --wait-for-video 10 --write-subs --sub-langs live_chat --write-thumbnail` it only downloads chat recently
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17520451/20de2757-c83d-4244-9aab-5fdd1ca40af2)
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17520451/d0955ffb-2d73-4a78-99af-0bd3f35ae475)

**Comment by ErrorFlynn** [comment]
This happens because yt-dlp can't download the chat and the video at the same time. It warns you of this:
`WARNING: Live chat download runs until the livestream ends. If you wish to download the video simultaneously, run a separate yt-dlp instance`.

So you need to be downloading the video with one instance of yt-dlp, and the chat with another. You can do that with ytdlp-interface by queuing the video twice, by using different URLs (the `youtube.com` URL you can get from the video tab of the channel, and the `youtu.be` URL you can get by right-clicking on the video player and selecting `Copy video URL`). Or, you could just run yt-dlp in a command prompt window to download the live chat, while ytdlp-interface downloads the video.

**Comment by MODKILLER1001** [comment]
so like https://www.youtube.com/watch?v=VideoID&https://youtu.be/VideoID

**Comment by ErrorFlynn** [comment]
> so like https://www.youtube.com/watch?v=VideoID&https://youtu.be/VideoID

`https://www.youtube.com/watch?v=VideoID`
or
`https://youtu.be/VideoID`
or
`https://www.youtube.com/watch?v=VideoID&`
or
`https://youtu.be/VideoID&`

Those are all distinct URLs that point to the same video. `yt-dlp` discards everything after the `&`, including the `&`. The `&` makes the URL distinct from the version without `&`, so you can add it twice to the queue in `ytdlp-interface` (because `ytdlp-interface` doesn't allow identical URLs to be added to the queue).

For example, `https://www.youtube.com/watch?v=cm-r25hY4VA&` is distinct from `https://www.youtube.com/watch?v=cm-r25hY4VA` because of the `&` at the end, even though it's functionally the same URL.
