### ISSUE TITLE
Error using old version of yt-dlp

### ISSUE THREAD

**Issue by JonnyThree** [ErrorFlynn/ytdlp-interface#133]
Hello i'm forced to use this great tool with an older custom version of yt-dlp, dated 2023.10.03. Since the version 2.10.0 of the interface, i can't download for a specific website because i got this error when i paste the link from the clipboard:
[GUI] got error executing command line: yt-dlp.exe --no-warnings --compat-options manifest-filesize-approx -j -o "%(title)s.%(ext)s" "https://www.discoveryplus.com/it/video/le-megastrutture-di-franco/stagione-1-episodio-6-la-valle-dei-caduti"

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: wrong OPTS for --compat-options: manifest-filesize-approx

I think the problem is in the added command line that the version 2.9.0 doesnt have:
--compat-options: manifest-filesize-approx

Do you have any suggestion to resolve this?

Edit: another link for testing (the previous needs a payed subscription)
https://www.discoveryplus.com/it/video/auto-storia-di-una-rivoluzione/stagione-2-episodio-10

this is the custom build of yt-dlp that i'm using:
https://github.com/bashonly/yt-dlp/releases/tag/2023.10.03.043124

**Comment by ErrorFlynn** [comment]
>I think the problem is in the added command line that the version 2.9.0 doesnt have:
--compat-options: manifest-filesize-approx

Yes, that's the problem. The program uses that option when getting info about the URL from yt-dlp. You can still download (just start the download and it should work), but you won't be able to access the formats list, or see the media title in the queue, because the program doesn't have that data.

I might release a patch version with a fix in the next few days if I have time (the usage of `--compat-options: manifest-filesize-approx` should be conditioned on the presence of a yt-dlp version recent enough to support it).

**Comment by JonnyThree** [comment]
ok very thanks for your support
