### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by sergizum** [ErrorFlynn/ytdlp-interface#141]
Hello! The update has not worked for several days now.
https://i.imgur.com/qUXmo5Z.png
Tnx!

**Comment by ErrorFlynn** [comment]
The update works for me, I don't know why it doesn't for you. It might be that you reached the quota for how many times you can access the GitHub API per day (but that would be hard to do), or maybe you have some other issue with reaching GitHub, or there's some other circumstance that I'm not aware of. Has it worked again at all since you posted 3 weeks ago?

I'm actually concerned with the font rendering issue that causes some text to clip in your screenshot (for example, `Latest version:`). Can I ask what system language you are using, so I can test with it and address the font rendering issue?

**Comment by ErrorFlynn** [comment]
>I'm actually concerned with the font rendering issue that causes some text to clip in your screenshot (for example, `Latest version:`). Can I ask what system language you are using, so I can test with it and address the font rendering issue?

Never mind, I fixed the issue.
