### ISSUE TITLE
API rate limit error

### ISSUE THREAD

**Issue by MInecrafterPictures** [ErrorFlynn/ytdlp-interface#168]
Also, I cannot update because it crashes.

**Comment by ErrorFlynn** [comment]
The API rate limit for non-authenticated users is 60 requests per hour. I imagine if you wait an hour it will reset and updating will work again. I don't know how you reached the limit, but one thing you can do to prevent reaching it, is to go to `Settings->Updater` and uncheck the option `Check at program startup and display any new version in the title bar`. 

>Also, I cannot update because it crashes.

It shouldn't crash, I'll look into it.

(I have removed your screenshot because it contained your IP address.)

**Comment by MInecrafterPictures** [comment]
I can't even select the Updater part without crashing

**Comment by MInecrafterPictures** [comment]
Also thanks for removing the screenshot. I did not noticed my ip address.

**Comment by ErrorFlynn** [comment]
I fixed the crash, the next version will contain the fix.
