### ISSUE TITLE
Cannot use own output in custom arguments

### ISSUE THREAD

**Issue by sn-o-w** [ErrorFlynn/ytdlp-interface#17]
It looks like no matter what custom arguments I use, I mean no matter what `-o name` is manually set as a custom argument, your app will ignore any custom output set in favor of default `%(title)s.%(ext)s`.

Can you make ytdlp-interface ignore the default output name if there's a custom argument set for the output name? 🤔

**Comment by ErrorFlynn** [comment]
In the next version, the custom arguments will always override the defaults, but I'm not sure about `-o` (because the output folder is part of it). If I can't find another way to give `yt-dlp` the output folder (which would allow for a custom `-o` to override the default), I guess I'll make the output template changeable in the settings. But yes, one way or another this issue should be addressed in the next version.
