### ISSUE TITLE
Auto number to playlist items

### ISSUE THREAD

**Issue by Lucifer-00007** [ErrorFlynn/ytdlp-interface#18]
It is a feature request!

If possible please add the option to give index to the playlist video.

**Comment by ErrorFlynn** [comment]
With the latest version (1.6), you can use a custom [output template](https://github.com/yt-dlp/yt-dlp#output-template) to index playlist videos. You could change the output template in the settings, but since this needs to only apply to playlist URLs, it's better to use a custom argument.

For example, using `-o "%(playlist_index)02d - %(title)s.%(ext)s"` as a custom argument would produce filenames like this: `01 - title.ext`. You can read the documentation for further customization, and make sure to enclose the template in quotes if it contains spaces (like in my example).

I don't plan to add playlist indexing as an explicit feature of the interface (it would clash with the user's ability to use a custom output template, among other reasons).

**Comment by ErrorFlynn** [comment]
I found a way to do it that makes sense, v1.7 indexes playlist videos.

**Comment by Lucifer-00007** [comment]
**Thank you so much!**
@ErrorFlynn
