### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by BeegDeek** [ErrorFlynn/ytdlp-interface#180]
All I get is the same error. Youtube must have changed the code again. You have to update the software. Websites like loader.to still work

**Comment by BeegDeek** [comment]
I already know that. It doesn't work anymore. Never assume anything. I've been on the web longer than you've been on Earth

**Comment by c-sanchez** [comment]
@ErrorFlynn Hi, In order not to create a new thread, I take advantage of this one to tell you, since some time ago the Updater does not work in my case, it gives me the error “failed to get from GitHub!”

![ytdlp-interface-updater](https://i.ibb.co/X5xjS7W/updater.png)

I wonder if it's something in my system or if it's a bug that happens to everyone.
Regards,

**Comment by BeegDeek** [comment]
The updater works I have the latest version. Youtube changed the code so they have to update their code

**Comment by BeegDeek** [comment]
It was just updated to 2.14.1 and now its working. So when Youtube changes the code I have to use a web downloader and wait for yt-dlp to update their code
