### ISSUE TITLE
Files away download in .mlv even though mp4 is set to preferred

### ISSUE THREAD

**Issue by SleepDaemon** [ErrorFlynn/ytdlp-interface#189]
The output file container is always mkv even though I have the preferred container set to mp4

**Comment by githottub** [comment]
You didn't provide examples so I can't specifically confirm but the most likely explanation is that the combination of audio and video codecs chosen are not compatible with the mp4 container and therefore must use mkv since it has much more flexibility/options for what media it can contain.

You can test that the mp4 container will be used as preferred if you manually select in the format window a video variant which shows mp4 in the ext column and an audio variant which shows m4a in the ext column. Those are both compatible with an mp4 container and therefore the result should be an mp4. If it is then the ytdlp-interface is working correctly.

**Comment by SleepDaemon** [comment]
> You didn't provide examples so I can't specifically confirm but the most likely explanation is that the combination of audio and video codecs chosen are not compatible with the mp4 container and therefore must use mkv since it has much more flexibility/options for what media it can contain.
> 
> You can test that the mp4 container will be used as preferred if you manually select in the format window a video variant which shows mp4 in the ext column and an audio variant which shows m4a in the ext column. Those are both compatible with an mp4 container and therefore the result should be an mp4. If it is then the ytdlp-interface is working correctly.

what i use, h264 so compatible with social media platforms
![image](https://github.com/user-attachments/assets/37d79af9-e0e1-4312-9469-e01f0d0e7124)

**Comment by githottub** [comment]
You haven't set a preferred audio codec. Therefore, if an audio codec which is incompatible with the MP4 container is either manually or automatically selected, it will result in an MKV container needing to be used.
