### ISSUE TITLE
wrong preferred format

### ISSUE THREAD

**Issue by nvnkx** [ErrorFlynn/ytdlp-interface#190]
i selected the mp4 format and the downloads appear in mkv or webm. help please 😭
![image](https://github.com/user-attachments/assets/e628aae8-8aea-46cc-ba05-46ee1aeb7e91)

**Comment by babzai** [comment]
I have the same issue

**Comment by ErrorFlynn** [comment]
YouTube doesn't use MP3, so yt-dlp selects the format it thinks is the best out of those available for that video, which is format 251 (Opus audio in a WebM container). The reason you don't get an `.mp4` file is because the mp4 container doesn't support Opus audio streams, so yt-dlp is forced to put the H264 video and the Opus audio into an `.mkv` container file which supports both.
