### ISSUE TITLE
Possible to integrate SponsorBlock ?

### ISSUE THREAD

**Issue by Lehner82** [ErrorFlynn/ytdlp-interface#2]
Have you looked into this ? Though its already really, really good.

**Comment by ErrorFlynn** [comment]
From the quick look I had right now, it seems that all you need to use SponsorBlock are the `--sponsorblock-` arguments for yt-dlp. I don't plan to explicitly integrate them into the interface, but the next version (coming soon) will allow the user to use custom arguments, so that should be enough I think.

**Comment by Lehner82** [comment]
Ok thats good to know. 
Also for some reason when I choose webm it always downloads the avc stream instead of the vp9 one. This doesn't happen in normal yt-dlp for me.

**Comment by ErrorFlynn** [comment]
> Also for some reason when I choose webm it always downloads the avc stream instead of the vp9 one.

I just tested, and it seems the argument `-S "res:1080,vcodec:webm,fps"` causes `yt-dlp` to select the formats `137+251` (mp4/avc video + webm/opus audio). For `-S "res:1080,vcodec:webm,acodec:webm,fps"`, it selects `137+140` (mp4/avc video + m4a audio). I don't know if I'm missing something, but that seems like a bug to me.

I guess the only way to avoid that, is to manually select the formats (go into settings and check "YouTube: show video info and list available formats").
