### ISSUE TITLE
UI Enhancement Request: Open File / Open Folder in context menu

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#23]
After downloading a video I often like to watch (open) the file/folder.
Please add such commands in the right mouse context menu.

**Comment by XCongoAlpha** [comment]
Agreed. This is what I am also waiting for.

**Comment by megabugman** [comment]
thank you for implementing the feature. as you wrote in the release notes "The Open files command isn't available 100%"

Instead of adding two commands (open file / open folder) of which one does not appear at all in my testings, I suggest to add a single command "Open file location" which is a standard command in Windows.

After selecting an item and running "Open file location" the download folder is opened in Windows Explorer AND the downloaded file is selected:

https://i.postimg.cc/MHfmv9t2/open-file-location.png

Now pressing Enter would run the file. I think this should work and would be more intuitive than having 2 (semi-broken) commands.

thanks for considering my enhancement request!

**Comment by ErrorFlynn** [comment]
The problem is that the program has to guess the file name (which is produced by yt-dlp, and which depends on a number of factors, including the various options that are passed to yt-dlp as command line arguments). 

If the program doesn't guess correctly (easily tested by seeing if the file exists), then the "open file" command doesn't appear, and "open folder" just opens the folder. When the guess is correct, "open folder" also selects the file. It makes sense to have both commands, because sometimes you want to open the file, and sometimes you just want to select it so you can move it or delete it.

Anyway, I will improve the filename detection in the next version (there are some ways of getting the filename from yt-dlp that I can try).
