### ISSUE TITLE
Clipping support

### ISSUE THREAD

**Issue by MODKILLER1001** [ErrorFlynn/ytdlp-interface#29]
Would it be possible to allow us to choice a starting timestamp and an ending timestamp so we can clip parts of videos down the the frame.

**Comment by MODKILLER1001** [comment]
I want to be able to like clip 0:00:01 - 0:00:14 https://www.youtube.com/watch?v=9Q34st0Ilvc, I know video wont be embeded in the application but just a place for me to manually set numbers for a timestamp

**Comment by ErrorFlynn** [comment]
I added support for this in v1.9 using yt-dlp's `--download-sections` option, which unfortunately downloads using `FFmpeg` and is very slow. There doesn't seem to be another way of doing it, so I guess this is as good as it gets.

**Comment by MODKILLER1001** [comment]
What would the --download-sections command look like as an example?

**Comment by MODKILLER1001** [comment]
As putting this in the video url area [https://www.youtube.com/clip/UgkxQa917T4n-QjP_XZzWV0GvuB-aQVt4-h4](https://www.youtube.com/clip/UgkxQa917T4n-QjP_XZzWV0GvuB-aQVt4-h4)
gives me this with lag

https://user-images.githubusercontent.com/17520451/219413090-1a5f6501-d09a-4657-924b-657daebf7eb3.mp4

**Comment by ErrorFlynn** [comment]
>What would the --download-sections command look like as an example?

If you click `Show output` in the interface, you can see the entire command line with all the arguments that are passed to yt-dlp, including `--download-sections`.

But since you asked, I can give you a couple of examples:
`--download-sections *10:15-11:0`
`--download-sections *12:0-inf`
That would download the sections from 10:15 to 11:00, and from 12:00 to the end of the media.

**Comment by ErrorFlynn** [comment]
Wait, you're asking because you think you have to use `--download-sections` manually? You don't have to do that, just add a video to the queue, select it, open the queue menu, and select `Download sections for item #...`. Then a window opens up where you can define sections to download. After you have defined your sections, just click `Start download` and the program takes care of the `--download-sections` arguments automatically. That's what I meant when I said I added support for it! Sorry for the miscommunication.
