### ISSUE TITLE
Doesnt download video, only audio

### ISSUE THREAD

**Issue by Ravn73** [ErrorFlynn/ytdlp-interface#30]
I got a problem. Everytime i want to download a video. It doesnt matter which one, it downloads the video and audio.  Then it erases the video permantly and automatic! All i get is the audio. Same thing when i let ytdlp choose the best format.

![1](https://user-images.githubusercontent.com/21908456/210079552-b1dda914-b5ee-43cc-b631-bcf8207e3852.png)
![2](https://user-images.githubusercontent.com/21908456/210079561-180f74fb-5220-43b7-9e95-aeb077410aea.png)

**Comment by ErrorFlynn** [comment]
It sounds like you have `Convert audio to MP3` checked. Only use that option if you want an `.mp3` file (audio only). All it is meant to do is to take the source audio and convert it to `MPEG Layer 3` format, and then save it to an `.mp3` container file (I will add an explanatory tooltip in the next version). If you use that option, you should download an audio-only format if available, otherwise the video will be discarded.

Also, YouTube doesn't use `MPEG Layer 3` audio, the only reason I added `mp3` to the list of preferred audio containers, is because some audio-oriented websites (like Souncloud or Bandcamp) may offer `mp3` files alongside other formats. No video website uses `MPEG Layer 3` audio tracks for the video files.

**Comment by Ravn73** [comment]
> It sounds like you have `Convert audio to MP3` checked. Only use that option if you want an `.mp3` file (audio only). All it is meant to do is to take the source audio and convert it to `MPEG Layer 3` format, and save it to an `.mp3` container file (I will add an explanatory tooltip in the next version). If you use that option, you should download an audio-only format if available, otherwise the video will be discarded.
> 
> Also, YouTube doesn't use `MPEG Layer 3` audio, the only reason I added `mp3` to the list of preferred audio containers, is because some audio-oriented websites (like Souncloud or Bandcamp) may offer `mp3` files alongside other formats. No video website uses `MPEG Layer 3` audio tracks for the video files.

That was it! Thank you and have a happy new year =)
