### ISSUE TITLE
Wait for video

### ISSUE THREAD

**Issue by djein-tap** [ErrorFlynn/ytdlp-interface#31]
Hi this issue may have been addressed elsewhere but I cant seem to find any information on it.
Since the queue function was added in V1.6 I no longer seem to be able to use the --wait-for-video function in the custom arguments that I could use on older versions such as V1.5.1.
I now get the error "yt-dlp failed to get info" and can no longer use current versions to wait for videos that are scheduled to go live.

**Comment by ErrorFlynn** [comment]
I can't find any videos scheduled to go live, so I can't test and understand what happens. If this doesn't change until the next version is released, I guess I'll just allow the download to be started when `--wait-for-video` is used, since it's probably just an issue with getting the metadata. I should probably allow all queue items with `error` status to be started, come to think about it.

**Comment by djein-tap** [comment]
Allowing the errored videos to start seems to have fixed the issue I had a chance to test it today and it appears to work as it should.
