### ISSUE TITLE
Special characters in video title causes program to crash

### ISSUE THREAD

**Issue by BillyFan359** [ErrorFlynn/ytdlp-interface#32]
Trying to download a video with for example é or korean/japanese characters, results in the program stuttering then crashing.

**Comment by ErrorFlynn** [comment]
I tried videos with Korean and Japanese characters and was unable to reproduce your crash (for example: https://www.youtube.com/watch?v=2XID_W4neJo). The only issue is that the characters don't show up in the output from yt-dlp, but otherwise everything works normally for me. Are you using the latest version?

**Comment by BillyFan359** [comment]
https://www.youtube.com/watch?v=oXok4kIB_iA this is one of the videos that has been producing crashes, should've included it. Using the latest version.

**Comment by ErrorFlynn** [comment]
It's not the CJK characters, it's actually the percent sign. Yes, the PERCENT SIGN. Wow.

I'm not sure if I'll release a patch version with the fix just yet, I'm still trying to find a "scheduled to go live" video to fix issue #31.
