### ISSUE TITLE
Shared FFmpeg builds

### ISSUE THREAD

**Issue by AHOHNMYC** [ErrorFlynn/ytdlp-interface#4]
Please, use shared FFmpeg builds. Instead of 2 files 100 MB each (200 MB total), you may reduce unpacked FFmpeg size to 100 MB.

**Comment by ErrorFlynn** [comment]
I don't know about this. In my experience with shared builds, there are always users who are missing the required DLLs, and don't know what to do about it. Besides, I just tested, and a 7z archive of `ffmpeg.exe` and `ffprobe.exe` is only 45.3MB. I know many people have data limits or slow connections, but is an extra 45.3MB that important? Personally, I'm inclined to continue using the static builds.

**Comment by AHOHNMYC** [comment]
![image](https://user-images.githubusercontent.com/24810600/163912164-3c1b7b7d-031e-4f5b-9f85-3db109528a8b.png)
![image](https://user-images.githubusercontent.com/24810600/163912410-8f944df0-f184-41b2-a0d9-419f3bc1607a.png)
I don't get your point about unresolved dependencies problem.
It is not Linux builds. The difference between static and shared builds is manner of using shared [between EXEs] code. As you can see above, dependencies are almost same. Dependencies on some system libraries are moved out to DLL (you may inspect it with any [Dependency walker](https://dependencywalker.com)).
So in the end both builds are want same DLLs from your OS. But shared is more compact.

> Also, who cares about the unpacked size?
Me. Why should I pay 100 MB to every program, instead of using that space to store video? It is not rational. There is no reason to eat space on drive, when you may reduce it w/o loss of functionality.

**Comment by ErrorFlynn** [comment]
>The difference between static and shared builds is manner of using shared [between EXEs] code.

That's not true. A shared (dynamically linked) build calls functions stored in external DLL files, while a statically linked build stores those functions in its own binary (which is why the binary is larger), so that it doesn't have to depend on DLL files.

You can see in your own screenshot that the shared build depends on a bunch of DLLs like `avcodec-59.dll`, that the static build doesn't depend on. If you delete or rename `avcodec-59.dll`, you will no longer be able to run the shared `ffmpeg.exe`, but the statically linked version will continue to run.

I actually didn't know ffmpeg linked to so many of its own DLLs, now it's clear that a random user isn't going to have those files installed, and wouldn't be able to use the shared build.
