### ISSUE TITLE
Default to selected formats, and playlists

### ISSUE THREAD

**Issue by dardoor** [ErrorFlynn/ytdlp-interface#42]
I was downloading a playlist of Youtube videos and there were a couple of small annoyances.

1. The pasted playlist link was not extracted to a list of individual items on the queue. It would be useful if it did that (maybe with a collapsible UI), also to have the ability to select the desired A/V formats for individual items (see point 2).

2. After adding each video separately, I had to click "Select formats" and then "Use the selected format(s)" for each item, because it always defaulted to "Let yt-dlp choose the best formats".
The formats that I selected for the previous video were _remembered_ for the next one, but they were not used. Maybe a setting to make "selected formats" the default would solve this.

Oh and thank you for making this. It's a nice app.

**Comment by ErrorFlynn** [comment]
>The pasted playlist link was not extracted to a list of individual items on the queue. It would be useful if it did that

I'm not aware of the utility of doing that, if you would give a specific example (other than selecting formats for each playlist item), then I'll consider it.

Your issue is that you want to be able to select the formats for yt-dlp to use for all the videos in the playlist. The problem is that there's no guarantee that all videos in a playlist have the same formats available (there's not even a guarantee that all the videos in a playlist belong to the same channel). There's no reasonable way of compiling a list of only the formats that are common to all videos in the playlist. It can be done, but I think it would take too much time, especially for playlists with hundreds or thousands of videos. Just the time it would take yt-dlp to obtain the info for each video in the playlist would be too much, in my opinion.

What I've decided to do for the next version, is to enable the "Select formats" button, and let the user select from the list of formats for the first video. That would cause yt-dlp to use those formats for each video in the playlist when available, and fall back to the default behavior when the formats aren't available.

For now, you can achieve the same effect by using a custom argument. For example, if you want video format `302` and audio format `251` for all videos in the playlist, you can use `-f 302+251` as a custom argument. Then yt-dlp will use those formats for each video that has those formats, and automatically select the best format for the rest, according to the preferences you set in the settings (resolution, video container, etc).

**Comment by dardoor** [comment]
All right, thanks. And good tip about the custom argument, I didn't think of that.

Your plan of inspecting the first video in a playlist would indeed solve the issue I was having.
But there might also be cases where a user would want to choose a different format for some of the videos in the playlist (also because, as you pointed out, they're not all available for every video). So for that, expanding the whole playlist could still be useful.
Other than that, I think having all playlist videos in the queue also looks better/neater (at least if it's not a huge playlist). But frankly, I rarely use these tools, so I don't know the typical use cases.
