### ISSUE TITLE
Dash Video

### ISSUE THREAD

**Issue by DajMiliona** [ErrorFlynn/ytdlp-interface#48]
Program has problems with DASH Video. Doesn't download Video and Audio.
Please add the command for Ffmpeg in the program. Example:

yt-dlp --downloader ffmpeg "https://sdt-epix13-44.tvp.pl/token/video/vod/69057678/20230411/3000535500/44546e57-2f23-4742-af8e-74c4d40feb89/video.ism/video-fmp4.m3u8"

**Comment by ErrorFlynn** [comment]
You can add `--downloader ffmpeg` as a custom argument, and you can start the download even if the queue status is `error`.

The problem for me is that `yt-dlp` can't access the webpage for the URL you provided. Initially I got `ERROR: [tvp] 69057678: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out')))`. Then I used a VPN with a Polish server, and still got this: `ERROR: [tvp] 69057678: Unable to download webpage: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>)`. This also happens when I use the command prompt.

What error are you getting?

**Comment by ErrorFlynn** [comment]
>How to download selected fragments via ffmpeg?

I don't know, I have very little knowledge of FFmpeg.

>Add options for resizing the program window. I have Windows 7. The program window is huge and cannot be reduced.

I'll see if I can lower the minimum size of the window in the next version.

**Comment by ErrorFlynn** [comment]
>Add options for resizing the program window. I have Windows 7. The program window is huge and cannot be reduced.

Just to be clear, the window has always been resizable. Are you not able to resize it? In any case, v2.1.0 (released today) lowers the minimum size by 100 pixels, so you can make the window even smaller now.
