### ISSUE TITLE
Removing item from queue causes app to not respond

### ISSUE THREAD

**Issue by f34r1335** [ErrorFlynn/ytdlp-interface#57]
Thanks for the new version. Found an issue when I individually remove an item from the queue, the app freezes. It doesn't seem to happen every time, but most of the time, so something about specific videos? If the queue has 2 or more videos and I use remove all it seems to work fine though.

Also a couple small display issues I noticed for the select formats window:

- The automatically chosen video format does not have the orange/brownish highlight, but 8k videos do seem to have the highlight.
- If there are many formats to choose from, a scrollbar will appear, but the height is still a bit too big and the buttons at the bottom get cut off (I only see around the top 1/3 to 1/2 of the buttons). Maybe this differs slightly across each setup?

**Comment by ErrorFlynn** [comment]
>Found an issue when I individually remove an item from the queue, the app freezes.

I've just released a patch version that fixes this, thanks for the report.

>The automatically chosen video format does not have the orange/brownish highlight, but 8k videos do seem to have the highlight.

That's very strange. I wasn't able to reproduce this, and looking briefly at the code, it seems physically impossible! In the next version, I'm going to remove that capability entirely, since it's no longer used (the formats that yt-dlp chooses are now indicated with an asterisk).

>If there are many formats to choose from, a scrollbar will appear, but the height is still a bit too big and the buttons at the bottom get cut off (I only see around the top 1/3 to 1/2 of the buttons). Maybe this differs slightly across each setup?

I'm guessing that's because you're not auto-hiding your taskbar. I forgot that's even a possibility! I'll see if I can fix this in the next version.
