### ISSUE TITLE
mp4 file format always converted to mkv

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#63]
whenever I download a video from YT the file is converted to mkv, I prefer mp4.
In Settings I have set mp4 as preferred video container.
Selecting mp4 only in "Select formats" dialog did not help.

So my question is: How to get mp4 not mkv files when downloading from YT?
As noticed in the output window the video is downloaded as mp4 but converted in the last step to mkv.

**Comment by altadr** [comment]
Not knowing if this can help: The same problem had occured when I tried (in 'settings' -> 'path to yt-dlp.exe') the alternative 'ytdl-patched-red.exe'. After switching back to 'yt-dlp.exe' that never happened again for me.

**Comment by ErrorFlynn** [comment]
Like `altadr` said, that can happen if you use [ytdl-patched](https://github.com/ytdl-patched/ytdl-patched) (`ytdl-patched-red.exe`), which always merges formats into the `mkv` container for some reason.

But what's likely happening in your case is that yt-dlp is combining the `.mp4` video with `.webm` audio (encoded with the `opus` codec), because that's the audio format that yt-dlp considers the best by default. And since the `.mp4` container can't contain `opus` audio, the formats are merged into an `.mkv` file.

In order to fix that, just go to settings and select `.m4a` as the preferred audio container, since that's compatible with `.mp4`.

**Comment by megabugman** [comment]
thank you for your replies. I use yt-dlp.exe, changing preferred audio container to m4a did the trick.

@ErrorFlynn maybe you want to make it more obvious, after selecting mp4 as preferred video container as tooltip or similar should be displayed to inform users that the audio container should be m4a. Or if mp4 is the default when starting ytdlp-interface for the first time then m4a should be preselected as audio container...

thanks again.

**Comment by megabugman** [comment]
thanks for adding the container tooltip to make it more clear
