### ISSUE TITLE
[Feature Request] Active download show output

### ISSUE THREAD

**Issue by ikeman2003** [ErrorFlynn/ytdlp-interface#64]
Add an option to show the output of the item that is currently downloading if its going through the queue

**Comment by ErrorFlynn** [comment]
You can see the output for the item that is currently downloading by double-clicking the item, or by selecting it and clicking the output button (if you prefer the hard way). 

Since double-clicking the item is easy enough to do, I'm not sure it's necessary to add another interface element that shows the output of the active download. I think the drawback of increasing the interface clutter outweighs the little benefit it would add. Also, it would not even be usable when there are two or more concurrent downloads.

I'll give this some more consideration, but right now I'm not sold on it.

**Comment by Korb** [comment]
@ikeman2003, I assume you meant something like the one implemented in the Download Master application, where part of the application window can be allocated to display the log of the download selected in the list:

![2024-07-30_10-01-25](https://github.com/user-attachments/assets/4382b410-3caa-47fb-9fb6-371dcefd4949)

This is a great idea and I support it. It is not obvious that double-clicking on a download switches the window to the log display mode, and does not start playback of the download or pause/resume downloading. Also, after switching the window to "Show queue" mode (I'll call it that because the title doesn't change), it's unclear for which download this log is displayed? In the case of split screen, it would be obvious and clear.
