### ISSUE TITLE
Cannot add extra columns if main window is close to screen edge

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#68]
I want to add "Format note" and "Filesize" but this cannot be achieved if main window is close to screen edge:
![bug](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/f89f54d9-35a8-4610-919e-773476d6ad8e)

**Comment by ErrorFlynn** [comment]
Thanks for reporting this. It seems to be a bug with the GUI library I'm using (https://github.com/cnjinhao/nana). Since that project is unmaintained right now, I'd have to fix the bug myself, or find some kind of workaround. I'll probably do that at some point, but in the meantime, you should just right-click on the queue to access the menu.
