### ISSUE TITLE
Audio preset and download with one click

### ISSUE THREAD

**Issue by trimechee** [ErrorFlynn/ytdlp-interface#7]
Hello,  it will be great please if there an option preset to choose by default to download the worst audio quality for a faster download, and possiblity to choosing the native audio quality "opus" or "m4a" ,  I use another program to automatically download the worst audio quality of youtube videos and I always get the audio quality with "opus" format with 64kbps bitrate or 48kbps bitrate and we would like to have the worst audio quality because I put these audios in my smaprtphone using the "snapdrop.net" sharing site and I would like to preserve the battery of smartphone by using the most worst audio quality, it will be great to add the "opus" 64kb/s audio format or "m4a" audio format  for the "worstaudio" preset!

Please I have an important suggestion,  it will be great to make the button "download" next to the "paste from clipboard" button for more speed, and also it will be amazing to merge and unify the "paste from clipboard" and "download" buttons into a single button with memorization of the "worstaudio" preset, so we can download audio or video just by clicking on a one and only unified button and we no longer need anymore to click on 2 distant buttons "paste from clip board" and "Download"!

Thank you so much for this wonderful software jewel of technology :)

**Comment by ErrorFlynn** [comment]
>Hello, it will be great please if there an option preset to choose by default to download the worst audio quality for a faster download, and possiblity to choosing the native audio quality "opus" or "m4a" , I use another program to automatically download the worst audio quality of youtube videos

I've thought about it, and I've concluded it doesn't makes sense to add that to the interface. It's a very niche feature, that you can replicate yourself by using custom arguments. To download the worst audio, just add `-f wa` as a custom argument (this downloads the worst audio-only format, and no video). To download the best video combined with the worst audio, use `-f bv,wa`.

Incidentally, the next version will improve the usage of custom arguments, by remembering multiple sets of them from which you can choose in a drop-down list (as opposed to remembering only the last set that was used).

>Please I have an important suggestion, it will be great to make the button "download" next to the "paste from clipboard" button for more speed, and also it will be amazing to merge and unify the "paste from clipboard" and "download" buttons into a single button with memorization of the "worstaudio" preset, so we can download audio or video just by clicking on a one and only unified button and we no longer need anymore to click on 2 distant buttons "paste from clip board" and "Download"!

I can understand the problem, but I don't agree with the solution you proposed. Instead, I've made it so you can use the keyboard to quickly get the download started. You will be able to start the download in about a second with this sequence of keys: `Ctrl+V`, `Enter`, `Enter`.

`Ctrl+V` pastes the link and focuses the `Download >>>` button, `Enter` moves to the download page and focues the `Begin download` button, and another `Enter` starts the download. Alternatively, you can use `Space` instead of `Enter`.

Thanks for the feedback!

**Comment by trimechee** [comment]
Oh wonderful !! thank you very muc for your precious help and all of these awesome fantastic improvements :)
