### ISSUE TITLE
Incorrect Filesize

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#71]
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/73f89f40-99d1-4969-91db-5b405491f938)
After downloading the filesize is 102mb on hard disk. Why is that?

**Comment by ErrorFlynn** [comment]
The filesize displayed in the queue column is taken from the field `filesize` if available, or otherwise from `filesize_approx` (you can inspect them with the JSON viewer). These are the same fields referred to in the documentation (https://github.com/yt-dlp/yt-dlp#filtering-formats). The file sizes in the formats window are what yt-dlp provides for each format in the `formats` array in the JSON data (again, feel free to explore in the JSON viewer).

I have rarely found any of these values to be accurate, but I think they've gotten worse since yt-dlp switched to the DASH downloading method to defeat YouTube throttling. I'm not sure how useful it is to have a "filesize" column at this point, maybe I'll replace it with something else in the future.

**Comment by megabugman** [comment]
Thank you for the explanation. Feel free to close this post or leave it open for reference.

**Comment by githottub** [comment]
Suggestion: Just change the name to "Approx. Filesize" or "~Filesize". Even though it is not completely accurate it can be helpful in some situations. For example, when downloading videos from Youtube (or other sites) and there are multiple encodings at the same resolution (e.g. h.264 and VP9) it helps to see the approximate filesize to determine which to pick. Yes, VP9 is more effective/efficient but if the h.264 version has a MUCH larger filesize, it may be the better quality file. There are other scenarious where seeing the ~filesize is helpful to some users. Also, if you wanted to free up screen real estate for unwanted info, you could make the columns right-clickable so that users could enable/disable columns to their preference.
