### ISSUE TITLE
Download Sections Issues

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#82]
There seems to be an issue with sections, I tried this video with Sections 1:20 to 1:40
https://www.youtube.com/watch?v=CduA0TULnow
the mp4 seems to be 20 secs only but when opening in video player 4 min are shown:

![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/bd099d4e-adb8-44d0-b59d-6b295c598031)

Secondly when selecting "Convert audio to MP3" to download only 20 secs audio, the mp3 is not cut but 4:12 min long.
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/2eacc89d-e054-4feb-98d4-b7621d2d1dbd)

**Comment by ErrorFlynn** [comment]
I was not able to reproduce this. I got a few seconds extra (due to the cuts not being at keyframes), but I didn't get the entire length of the video. I tried with the versions of yt-dlp and ffmpeg that are packed with v2.4.0, and also with the latest versions.

Do you see `--download-sections *1:20-1:40` in the command line? If so, then whatever is happening is _probably_ not the program's fault.

**Comment by megabugman** [comment]
Issue is no longer reproducible. works as expected for video and mp3. thank you for your support.
