### ISSUE TITLE
drag a link from web browser seems not to work

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#91]
copy/paste works, but drag and drop not, tried with FF and chrome
![bug](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/1809af98-44ad-4878-9f1c-337857164ed4)

**Comment by ErrorFlynn** [comment]
I could not reproduce your Firefox attempt (worked fine for me).

For your Chrome attempt, it seems that you're not actually dragging a URL, but the title of the video (it's visible in the tooltip next to the cursor for a few frames of the video). Also, be aware that the program needs the protocol part of the URL (`https://`) to be present in order to recognize the dropped text as an URL.

**Comment by megabugman** [comment]
tried again, 3 different browsers. works as expected. sorry.
