### ISSUE TITLE
some commands are missing in context menu if only one item is present

### ISSUE THREAD

**Issue by megabugman** [ErrorFlynn/ytdlp-interface#92]
here some commands are missing:
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/514e946f-5151-4132-bb76-3de6db0233f7)

after adding a second item more commands are available:
![image](https://github.com/ErrorFlynn/ytdlp-interface/assets/17204819/1f9bbf4c-e078-4906-b9ae-a45002c6c291)

**Comment by ErrorFlynn** [comment]
That's on purpose, because the commands you highlighted with the green frame are superfluous when only one queue item exists. For example, if only one item is queued, `Remove all` does the same thing as `Remove item #1`. And if the item is completed, you can add `Clear completed` to that equivalence.

An argument could be made that the superfluous commands should be there anyway to satisfy habitual use, but personally I prefer a less cluttered menu.

**Comment by megabugman** [comment]
thanks for explaining
