### ISSUE TITLE
Project partially resumed

### ISSUE THREAD

**Issue by ErrorFlynn** [ErrorFlynn/ytdlp-interface#94]
>I'm currently going through some personal issues, and I haven't been able to work on this project since the last version. It looks like this is going to be long term, so I'm just letting everyone know that I don't know when this project will be updated and to what extent. Thanks for understanding.

>Edit: I will continue to keep an eye on the issues page, and will probably be able to release small updates (but at a slower pace than usual).

2nd edit: It looks like I'll be able to resume working on this to a partial but significant extent. I won't be releasing a new version every two weeks or so like before, but hopefully once a month or so.

**Comment by githottub** [comment]
Thanks for letting us know and best of luck with everything!

**Comment by githottub** [comment]
Thanks again for letting us know. I think once per month (or even just as needed) is perfectly reasonable. The main thing is take care of your personal life and don't let this project start feeling like a chore otherwise you'll just want to stop completely. And that would be a shame because it's definitely the best overall app of its kind and worth maintaining.
