### ISSUE TITLE
[Feature Request] Select videos from a channel's list

### ISSUE THREAD

**Issue by altadr** [ErrorFlynn/ytdlp-interface#98]
It could be very helpful if a [channel tab] possibly could be handled like a [playlist], with context menu item 'Select which videos to download from'. Maybe it is only a minor adaption? 
Thank you very much for still improving ytdlp-interface, 
and best wishes!

**Comment by ErrorFlynn** [comment]
It would be trivial for the interface to treat channel tabs as playlists, but the problem is that it can take yt-dlp an unreasonably long time to retrieve all the video data. Some video tabs contain thousands of videos, for example, so you could wait several minutes for yt-dlp to collect all that data. I think a good compromise would be to make this behavior optional (I'll see what I can do).

**Comment by ErrorFlynn** [comment]
The next version will add a new context menu item for YouTube channel tabs: `Treat as playlist`
